"""Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
"""

import numpy as np
import numpy.typing as npt


def get_fibonacci_below_target(target: int) -> npt.NDArray:
    a = 1
    b = 2
    fibonacci_series = [1, 2]
    while a + b < target:
        next_val = a + b
        a = b
        b = next_val
        fibonacci_series.append(next_val)

    return np.array(fibonacci_series)


def main():
    fib_array = get_fibonacci_below_target(4_000_000)
    evens = fib_array[fib_array % 2 == 0]
    print(evens)
    print(evens.sum())


if __name__ == "__main__":
    main()
