"""Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
"""

from collections.abc import Iterator

import numpy as np
import numpy.typing as npt


def get_fibonacci_below_target(target: int) -> npt.NDArray:
    """Original solution"""
    a = 1
    b = 2
    fibonacci_series = [1, 2]
    while a + b < target:
        fibonacci_series.append(a + b)
        a, b = b, a + b

    return np.array(fibonacci_series)


def get_fibonacci_below_target_generator(target: int) -> Iterator[int]:
    """Generator function solution"""
    a, b = 1, 2
    while a <= target:
        yield a
        a, b = b, a + b


def main():
    # original solution
    fib_array = get_fibonacci_below_target(4_000_000)
    evens = fib_array[fib_array % 2 == 0]
    print(evens)
    print(evens.sum())

    # Generator solution
    fib_list = [
        n for n in get_fibonacci_below_target_generator(4_000_000) if n % 2 == 0
    ]
    print(fib_list)
    print(sum(n for n in get_fibonacci_below_target_generator(4_000_000) if n % 2 == 0))


if __name__ == "__main__":
    main()
